sonar.organization=bryzgin
sonar.projectKey=bryzgin_python-project-50
sonar.projectName=python-project-50

sonar.sources=gendiff
sonar.tests=tests

sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
